name: Run Shell Script on Remote Server
on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest  # You can change this based on your OS requirement

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up SSH key using the GitHub secret
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure the key is stored in GitHub secrets

    # Step 3: Run shell script on the remote server
    - name: Run script on remote server
      run: |
        ssh -o StrictHostKeyChecking=no -T nearbybasket@194.164.149.25 << 'EOF'
          ls -la
        EOF
