name: Deploy Application on Remote Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  # Job 1: Set up SSH key and checkout code
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  # Job 2: Git pull to update the repository on the remote server
  git_pull:
    runs-on: ubuntu-latest
    needs: setup  # This job depends on the 'setup' job to run first

    steps:
      - name: Pull latest code from the remote repository
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/nearbybasket/htdocs/nearbybasket.com/nearbybasket-web-next-js  # Navigate to your project directory
            ls -la
          EOF

 

